server:
  #port: ${PORT:${SERVER_PORT:0}}
  port: 8001
spring:
  application:
    name: ms-agencia-usuario
  config:
    import: configserver:http://localhost:8085
    name: ms-agencia-usuario
  profiles:
    active: test

springdoc:
  api-docs:
    enabled: true
  paths-to-match: /agencias/**, /usuarios/**
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html