server:
  port: 8085
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KevinVR14/config-server-agencia-usuario
          repos:
            ms-agencia-usuario:
              uri: https://github.com/KevinVR14/config-server-agencia-usuario
              clone-on-start: true
              #username: KevinVR14
              #password: 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
            ms-cliente-producto:
              uri: https://github.com/KevinVR14/config-server-cliente-producto
              clone-on-start: true
              #username: KevinVR14
              #password: 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
            ms-inventario-factura:
              uri: https://github.com/KevinVR14/config-server-inventario-factura
              clone-on-start: true
              #username: KevinVR14
              #password: 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
