server:
  #port: ${PORT:${SERVER_PORT:0}}
  port: 8003
spring:
  application:
    name: ms-inventario-factura
  config:
    import: optional:configserver:http://localhost:8085
    name: ms-inventario-factura

springdoc:
  api-docs:
    enabled: true
  paths-to-match: /facturas/**, /inventarios/**, /pedidos/**
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

aws:
  access:
    key:
      id:
  region:
  s3:
    bucket:
      name:
  secret:
    access:
      key: